### PR TITLE
Fix/async compile warnings

### LINKED ISSUE #165: Byte compile produces warnings for unknown functions
```
 ■  Warning (comp): citeproc-s.el:240:21: Warning: the function ‘citeproc-s-replace’ is not known to be defined.
 ■  Warning (comp): citeproc-lib.el:159:33: Warning: the function ‘citeproc-rt-render-affixes’ is not known to be defined.
 ■  Warning (comp): citeproc-lib.el:154:55: Warning: the function ‘citeproc-context-vars’ is not known to be defined.
 ■  Warning (comp): citeproc-rt.el:538:25: Warning: the function ‘citeproc-itemdata-rawbibitem’ is not known to be defined.
 ■  Warning (comp): citeproc-prange.el:40:44: Warning: the function ‘citeproc-s-fill-copy’ is not known to be defined.
 ■  Warning (comp): citeproc-date.el:271:13: Warning: the function ‘citeproc-number--format-as-ordinal’ is not known to be defined.
 ■  Warning (comp): citeproc-formatters.el:384:48: Warning: the function ‘citeproc-rt-to-plain’ is not known to be defined.
 ■  Warning (comp): citeproc-formatters.el:164:21: Warning: the function ‘citeproc-s-replace-all-seq’ is not known to be defined.
 ■  Warning (comp): citeproc-sort.el:90:19: Warning: the function ‘citeproc-number-var-value’ is not known to be defined.
```

### PR DESCRIPTION
**Pull request by Forge36**
Fixes #165

### CODE REVIEW

**Comment by Forge36** [comment]
Branch has errors now flagged with WIP commit

error:

`byte-code: Recursive ‘require’ for feature ‘citeproc-lib’`

**Comment by Forge36** [comment]
Removed fixes which caused fatal errors and fixed typo in the require

This leaves the following warnings:

```
 ■  Warning (comp): citeproc-lib.el:159:33: Warning: the function ‘citeproc-rt-render-affixes’ is not known to be defined.
 ■  Warning (comp): citeproc-lib.el:154:55: Warning: the function ‘citeproc-context-vars’ is not known to be defined.
 ■  Warning (comp): citeproc-rt.el:538:25: Warning: the function ‘citeproc-itemdata-rawbibitem’ is not known to be defined.
```

**Comment by Forge36** [comment]
This declares functions with parameters when I can determine them. Given my unfamiliarity with constructors I've declared the function without parameter validation.

**Comment by andras-simonyi** [comment]
Thanks a lot for the problem description and the MR! I've managed to reproduce the problems and merged a PR partly based on your suggested changes (#169). Could you check whether it has fixed the problems you were encountering?

**Comment by Forge36** [comment]
Issue fixed upstream! :)

**Pull request closed without merging**
