### PR TITLE
17 Sub-bibliographies

### PR DESCRIPTION
**Pull request by andras-simonyi**
Add support for defining and rendering filter-based sub-bibliographies

### CODE REVIEW

**Comment by denismaier** [comment]
Do you know if that feature is already available in orgmode?

**Comment by andras-simonyi** [comment]
Unfortunately it hasn't yet been integrated into oc-csl.

**Comment by denismaier** [comment]
Too bad. Would you do that? Or should I raise that issue on the org-list? @bdarcus WDYT?

**Comment by bdarcus** [comment]
There was already a thread on this on the list earlier; right?

The only reason to raise it on the list now is if there's uncertainty about implementation, and there's reasonable likelihood someone else will have time, capability, and interest to do it.

I doubt either applies, since it could just borrow the same approach as in oc-biblatex, and we've seen very little activity with patches like these so far.

OTOH, you could fully test oc-biblatex support for this, and if you run into problems with it, post a note on the list? That could then benefit oc-csl if and when someone finds time to implement it?

**Comment by andras-simonyi** [comment]
> I doubt either applies, since it could just borrow the same approach as in oc-biblatex, and we've seen very little activity with patches like these so far.

I wasn't aware that oc-biblatex already supports sub-bibliographies...

**Comment by bdarcus** [comment]
> I wasn't aware that oc-biblatex already supports sub-bibliographies...

Oh; now that I think about it, I'm not sure either.

I just vaguely I recall I saw this, or similar, support.

Obviously that would be something Denis could check out :-)

**Comment by denismaier** [comment]
I think it's in oc-biblatex. IIUC, @ebouna uses that already, right?

**Comment by bdarcus** [comment]
From the docstrings; this?

```elisp
#+print_bibliography: :section 2 :heading subbibliography
```

**Comment by ebouna** [comment]
> I think it's in oc-biblatex. IIUC, @ebouna uses that already, right?

Yes, I am using it!

**Comment by andras-simonyi** [comment]
FYI, I've made some improvements in this area and now the following types of filters are supported:
`type`, `nottype`, `keyword`, `notkeyword`, `csltype`, `notcsltype`, `filter`. The last three are new, and make it possible (i) to choose whether to match based on bib(la)tex type (if available) or CSL type, and (ii) to filter using any Emacs Lisp function. 
Perhaps more importantly, I have now a working `oc-csl.el` patch which adds support for filter-based sub-bibliographies to the csl org-cite export processor (`nocite` support has already been  merged.), I plan to test it a bit more and then send it to the Org mailing list.

**Comment by andras-simonyi** [comment]
Update: I've just sent the patch to the mailing list and don't expect major changes functionality-wise. Any comments, especially based on testing would be appreciated.

**Comment by andras-simonyi** [comment]
Further update: This feature has just been merged into Org's main ("master") branch, so should be available in the next version.

**Pull request merged**
